---
title: "Tiemseries_R"
author: "Sangyeol_lee"
output:
  html_document:
    keep_md: yes
---

```{r}
AR.ts <- scan(file="AR.ex.txt")
plot(AR.ts,type="l")
acf(AR.ts)
```

```{r}
imp.df <- read.table("Import.txt",header=T, row.names="year")
imp.ts <- ts(imp.df,start=1965)
plot(imp.ts)
acf(imp.ts)
```

```{r}
set.seed(123)
w.noise<-arima.sim(model=list(order=c(0,0,0)), n=200)
plot(w.noise)
```

```{r}
set.seed(123)
r.walk<-rnorm(100,mean=0.5,sd=sqrt(2))
plot(cumsum(r.walk),type="l")
```

```{r}
set.seed(123)
MA2 <- arima.sim(model=list(ma=c(0.6,0.3)),n=200)
plot(MA2)
```

```{r}
set.seed(123)
MA3 <- arima.sim(model=list(ma=c(0.5,0.2,0.1)),n=10^4)
arima(MA3,order=c(0,0,3),include.mean=F)
```

```{r}
set.seed(123)
AR2<-arima.sim(model=list(ar=c(1,-0.5)),n=200)
plot(AR2)
```

```{r}
set.seed(123)
AR1<-arima.sim(model=list(ar=c(0.9)),n=10^4)
arima(AR1,order=c(1,0,0),include.mean=F)
```

```{r}
set.seed(123)
ARMA11 <-arima.sim(model=list(ar=0.5,ma=0.4),n=200)
plot(ARMA11)
```

```{r}
set.seed(123)
ARMA11 <-arima.sim(model=list(ar=0.6,ma=-0.3),n=10^4)
arima(ARMA11,order=c(1,0,1),include.mean=F)
```

```{r}
set.seed(123)
first.AR1<-arima.sim(model=list(ar=0.7),n=100)
acf(first.AR1,lag.max=20)
acf(first.AR1,lag.max=20,type="partial")

second.AR1<-arima.sim(model=list(ar=-0.7),n=100)
acf(second.AR1,lag.max=20)
acf(second.AR1,lag.max=20,type="partial")
```

```{r}
kospi<-read.table(file="KOSPI.txt",row.names=1)
kospi.ts<-ts(kospi,start=c(1999,12),frequency=12)
returns<-log(kospi.ts/lag(kospi.ts,k=-1))
plot(kospi.ts)
M<-c(5,10,15)
for(i in 1:length(M)){
 print(Box.test(returns,lag=M[i],type="Ljung-Box")) 
}
```

```{r}
trade<-read.table("Property.txt", header=T, row.names=1)
tde.ts<-ts(trade,start=1973)
library(TTR)
plot(tde.ts,lwd=2,main="Moving Average")
lines(SMA(tde.ts,n=3),lwd=2,lty=2,col="blue")
lines(SMA(tde.ts,n=6),lwd=2,lty=6,col="red")
legend(1975,170,legend=c("original","3P","6P"),lty=c(1,2,6),col=c("black","blue","red"),lwd=2)
```

```{r}
exp.smt<-function(x,alpha){
  for(i in 1:length(x)){
    if(i==1) res<-x[i] else
      res<-append(res,alpha*x[i]+(1-alpha)*res[i-1],after=i-1)
    }
  res<-ts(res,start=tsp(x)[1],frequency=tsp(x)[3])
  }
plot(tde.ts,lwd=2,main="Exponential Smoothing")
lines(exp.smt(tde.ts,0.4),lwd=2,lty=2,col="red")
lines(exp.smt(tde.ts,0.7),lwd=2,lty=6,col="blue")
legend(1975,170,legend=c("original","0.4E","0.7E"),lty=c(1,2,6),col=c("black","red","blue"),lwd=2)
```

```{r}
library(tseries)
adf.test(imp.ts)
m1gdpd<-read.table("M1GDPd.txt",header=T,row.names=1)
m1.res<-lm(M1~GDP.def,data=m1gdpd)
m1.resid<-resid(m1.res)
adf.test(m1.resid)
```

```{r}
DowKos<-read.table("DowKospi.txt",header=T,row.names=1)
lm.res<-lm(Kospi~Dow,data=DowKos)
adf.test(resid(lm.res))
library(tsDyn)
VECM.res<-VECM(DowKos,lag=2,include="const",estim="2OLS")
summary(VECM.res)
```

```{r}
attach(m1gdpd)
M1.r<-diff(M1)/M1[1:length(M1)-1]*100
P.r<-diff(GDP.def)/GDP.def[1:length(M1)-1]*100
detach(m1gdpd)
M1P.df<-data.frame(M1.r,P.r)
library(vars)
VAR.res<-VAR(M1P.df,type="const",lag.max=4,ic="SC")
summary(VAR.res)
```

```{r}
library(urca)
joh.test<-ca.jo(m1gdpd,type="trace",ecdet="trend",spec="longrun")
summary(joh.test)
```

```{r}
library(FinTS)
ex.returns<-scan("Ex.returns.txt")
for(i in c(2,5,10)) print(ArchTest(ex.returns,lags=i))
library(rugarch)
ex.spec<-ugarchspec(variance.model=list(garchOrder=c(2,0)),mean.model=list(armaOrder=c(2,0)))
arch2<-ugarchfit(spec=ex.spec,data=ex.returns)
arch2
#plot(arch2)
spec.E<-ugarchspec(variance.model=list(model="eGARCH",garchOrder=c(1,1)),mean.model=list(armaOrder=c(0,0)))
egarch.res<-ugarchfit(spec=spec.E,data=ex.returns)
egarch.res
#plot(egarch.res)
spec.GJR<-ugarchspec(variance.model=list(model="gjrGARCH",garchOrder=c(1,1)),mean.model=list(armaOrder=c(0,0)))
gjrgarch.res<-ugarchfit(spec=spec.GJR,data=ex.returns)
gjrgarch.res
#plot(gjrgarch.res)
```                                                                          
                                                                           
                                                                           
                                                                           