---
title: "practice"
output: html_document
---

## 문제 1) GDP.rate에 경제성장률 값을 할당하고 출력하시오


## 문제 2

### 2-1) Unem.rate에 연도별실업률 값을할당 후 GDP.rate와 동시에 출력하시오

### 2-2) Unem.rate의 길이, 유형, 클래스 확인


## 문제 3) 12개 관측값을 WDrate로 할당, 각 원소 이름할당, 출력

## 문제 4

### 4-1) 커피판매자료를 coffee에할당, 범주화자료로 변환(Amer,Latte,Cappu) 후coffee.fct에 새롭게 할당, 결과출력

### 4-2) Latte의 판매비율

## 문제 5 

### 5-1) 모형계수행렬A를 정의하고 출력해라. 
변수는 Qd1, Qs1, P1, Qd2, Qs2, p2순서로 배열하고, 
행의 이름은 equ1~equ6 의 형태로, 열의 이름은 각각 변수이름으로 입력

### 5-2) 행렬의 속성을 확인

## 문제 6

### 6-1) 주어진 자료를 첫번째 차원은 국가, 두번째 차원은 변수, 세 번째 차원은 연도로 하는 3차원 형태로 배열

### 6-2) 11,12년도 한국, 영국, 유료지역 달러환산 빅맥가격 평균과 표준편차를 구하고 3개국가 빅맥의 현지 통화가격을 계신하여 새로운 배열을 구성

#### step1.빅맥가격의 평균과 표준편차

#### step2. 3개국가 빅맥의 현지통화 가격을 계산

#### step3. 새로운 배열 생성

## 문제 7

### 7-1) 표자료를 데이터프레임으로 구성

### 7-2) 연도별 물가상승률과 실질경제성장률 관측값을 합하여 새로운 벡터 할당후 데이터프레임의 네번째 변수로 추가

### 7-3) 실질경제성장률의 6년간 기하평군을 구하고 물가상승요인이 작용한 해를 확인해라

## 문제 8) 평균50, 분산9 인 정규분포 난수 30개 생성 / 난수는 소수점 셋째자리에서 반올림, 언제나 동일한 난수를 생상하여 사용할수있도록 시드번호 1734입력.

### 8-1) 데이터 총합, 데이터의 범위

### 8-2) 데이터 내림차순정렬, 평균값, 중앙값, 표준편차

### 8-3) 데이터 20%, 40%, 60%, 80%분위수, 요약통계량

### 8-4) 종료시점 2013년 관측주기 1개월 시계열 자료생성, 시차지연함수 사용하여 1년 시차 지연효과를 적용해보라
